call run_P1_during_training_always.bat
call score_P1_during_training_always.bat
call run_P2_during_training_always.bat
call score_P2_during_training_always.bat
call run_P3_during_training_always.bat
call score_P3_during_training_always.bat
call run_P4_during_training_always.bat
call score_P4_during_training_always.bat
call run_P5_during_training_always.bat
call score_P5_during_training_always.bat
call run_P6_during_training_always.bat
call score_P6_during_training_always.bat



